### ISSUE TITLE
Make headers compatible with C++

### ISSUE THREAD

**Issue by cesarvandevelde** [embedded-office/canopen-stack#10]
**Description**

As of yet, the headers of this library are incompatible with C++.
The underlying issues are twofold, but should be easy to fix. 

* The function prototypes are not declared with C linkage when included in a C++ file.
* The `co_types.h` header attempts to overwrite C++ keywords such as `bool`.

**Steps to Reproduce**

1. Include `co_core.h` inside a C++ file and compile:

```C++
#include "co_core.h"
```

```
canopen-stack/canopen/include/co_types.h:41:26: error: redeclaration of C++ built-in type 'bool' [-fpermissive]
canopen-stack/canopen/include/co_types.h:38: warning: "NULL" redefined
co_callbacks.cpp:64:9: error: conflicting declaration of 'int16_t COLssStore(uint32_t, uint8_t)' with 'C' linkage
...
```

2. Include using an `extern "C"` block:

```C++
extern "C" {
    #include "co_core.h"
}
```

```
canopen-stack/canopen/include/co_types.h:41:26: error: redeclaration of C++ built-in type 'bool' [-fpermissive]
canopen-stack/canopen/include/co_types.h:38: warning: "NULL" redefined
```

3. Force `co_types.h` to stop redefining `bool` and `NULL` by manually defining C-specific preprocessor symbols.

```C++
extern "C" {
    #pragma push_macro("__STD_C__")
    #pragma push_macro("__STDC_VERSION__")

    #define __STD_C__        1
    #define __STDC_VERSION__ 201112L
    #include "co_core.h"

    #pragma pop_macro("__STD_C__")
    #pragma pop_macro("__STDC_VERSION__")
}
```

**Expected behavior**

Ideally, one should be able to include `co_core.h` inside a C++ file as-is, without special preprocessor manoeuvres.

The C-linkage issue can be solved by wrapping all headers in the following construct:

```C++
#ifdef __cplusplus
extern "C" {
#endif

// Header contents

#ifdef __cplusplus
}
#endif
```

The issue with `co_types.h` could be solved by adding another defined check:

```C
#if defined(__STDC__) && (__STDC_VERSION__ >= 199901L) ||       /* ANSI C99 */\
    defined(_MSC_VER) || \
    defined(__cplusplus)
```

**Environment (If Necessary)**

- Target: STM32F103
- Cross-Compiler: GNU Arm embedded toolchain 9-2020-q2-update
- CANopen Stack: 4.0.1

**Comment by michael-hillmann** [comment]
Thanks. We will include your correction in the next release.
