### ISSUE TITLE
Small error in quickstart mandatory objects documentation

### ISSUE THREAD

**Issue by michael-hillmann** [embedded-office/canopen-stack#12]
Within the mandatory object entries of the quickstart documentation, the table row for identity object 1018h subindex 0h holds a wrong value (1). This value should be 4, because we provide entries for subindex 1 to 4 (Note: source code is correct).

**Comment by cesarvandevelde** [comment]
Another small typo in the [quickstart guide](https://canopen-stack.org/docs/start/quickstart#hardware-connection):   
`CO_TMR_TICK_PER_SEC` should be `CO_TMR_TICKS_PER_SEC`.
