### ISSUE TITLE
Not able to find object dictionary file in the stack and no idea which tool need to use to generate the EDS file

### ISSUE THREAD

**Issue by ankit-eic** [embedded-office/canopen-stack#124]
Hello,

I need some information for the object dictionary and EDS file which is required when we are running the conformance test tool to pass the CANOpen stack.

So, I cannot find the object dictionary file for the CANOpen stack in this stack and do not know which tool to use to generate the EDS file for a node to pass the conformance test tool.

Could anyone please give some insight on the above queries?

Thanks,
Ankit

**Comment by ankit-eic** [comment]
Hi,

Could I get any update on the above question? Thanks in advance.

Regards,
Ankit

**Comment by michael-hillmann** [comment]
Hi, there is no tool for EDS file generation. We are working most of the time the other way round: the EDS file is the specification for the implementation.

Regarding the object dictionary, please have a look to the quickstart on the project website. This explains how you implement an example dictionary.

In your project, you need a specification of the object dictionary, which cannot be part of a free generic CANopen stack.

**Comment by ankit-eic** [comment]
Hello, Thanks for the clarification on the object dictionary part. How I can get to know about the commercial CANopen stack?

**Comment by michael-hillmann** [comment]
Hi, there is no commercial CANopen stack. You can use this stack for free and may buy some assistance for your team to focus your project workload on the application.
