### ISSUE TITLE
Implementation on TI C2000 MCU with 16-bit bytes

### ISSUE THREAD

**Issue by wjklimek1** [embedded-office/canopen-stack#125]
Hello,
I want to use your CANopen stack on Texas Instrument F28062 microcontroller, which directly supports only 16-bit memory access. As a result, the smallest variable I can use is `uint16_t` and `sizeof(uint32_t)` returns 2, not 4. It creates some problems with casting variables in libraries developed in 8-bit access in mind. For example, casting `uint8_t array[4]` to single `uint32_t` is not possible, but `uint16_t array[2]` to `uint32_t` is. If i need to cast array of 4 bytes, for example received from SPI, to `uint32_t` I need to do it using bit shifting and OR-ing.

Obvious solution to implement your stack is just to replace all `uint8_t` with `uint16_t`. It seems in most cases it would work fine. However, I am a bit concerned about buffers casted to `void` in functions reading buffers in `co_obj.c` file and maybe other places I didn't notice.

If you can give me any directions about implementation on this weird C2000 architecture I will be very grateful. Your stack is well written and documented, I really appreciate effort that you put into it.

**Comment by wjklimek1** [comment]
Ok, so it finally works. I first implemented it on STM32 to get familiar with stack and have a 100% working example. Then I prodeeded with porting it to C2000.

Here are the steps that I had to take:
1) Implement all hardware driver functions for CAN and timer 
2) Replace all uint8_t with uint16_t
3) Replace all calls to sizeof() in a stack with static values compatible with 8-bit architecture, i.e. `sizeof(uint32_t)` with `4`, `sizeof(uint16_t)` with `2` and `sizeof(uint8_t)` with `1`

For now, the "clock" example works fine. I haven't perform any other test though, so more issues may show up in a future. Currently, I have PDO, SDO, NMT and heartbeat working properly.

**Comment by michael-hillmann** [comment]
Hi, great to hear that it is working for you now.

Regarding your steps, you have to take:
- well, ok - that is needed for all targets. I just in thinking of adding a common driver repository with multiple targets in the future (no decision yet).
- Hmm, can you explain, why this is neccessary. This change is hard to integrate in the stack, because the users with 8bit microcontrollers will not be happy...
- Ok, this change we can take over in the common stack sources. Should not be a problem.

I remember in a former project, that I need to mask values in a DSP to get ANSI-C compliant values. Maybe, this can help us to get a canopen stack which suits the needs for DSPs, too?

```c
voif foo(uint8_t *ptr)
{
  uint8_t val = *ptr & 0xFFu;
   :
}
```

**Comment by wjklimek1** [comment]
Hi, as I mentioned in the original question, Texas Instruments C2000 microcontrollers do not support 8 bit memory access. Like you can't declare `uint4_t` variable in ARM, you can't declare `uint8_t` on C2000. Of course it is possible to get access to 8 bit aligned memory using unions or bit shifting, but this workaround brakes when pointers are used. And of course, `sizeof` still returns values expressed in 16 bit bytes. 

I don't expect that you will introduce any of these changes to the stack, I just described my solution to help other programmers working on C2000. After all, 16 bit microcontrollers are a minority today and I don't think it is worth it to decrease stack performance to support them out of the box.

**Comment by michael-hillmann** [comment]
Ok, I just want to get a feeling if it could be possible to result in a version which is working on both: 16bit addressing machines & 8bit addressing machines (and even on 32bit addressing machines like the big TI DSPs)

Thanks for your effort!

**Comment by sicrisembay** [comment]
Hi @wjklimek1 
I did some porting of CANopen to c2000.  It was quite a mess but it works.
Mine is based on different project though, CANopenNode.
https://github.com/sicrisembay/CANopenNode_C2000

If it's ok, can you share also your source of your C2000 port?

**Comment by wjklimek1** [comment]
Hi @sicrisembay 
Sorry but I can't share the source code because it is part of a bigger project. But if you follow my hints from the previous post, you will easily make your own implementation. One additional thing that I discovered later is necessity to handle special case of string data types if string is shorter than 4 characters. You have to modify ` COTStringRead` function in co_string.c file to pack string data to the buffer like it was 8bit aligned in case the string is shorter than 4 chars. 

Hardware initialization is a whole different story but it goes outside the scope of this issue. I implemented eCAN library on registers and used circular buffers with interrupts to handle data transmission and reception. As a timer I used CPUTIMER2 with frequency of 1MHz, as suggested in examples.
