### ISSUE TITLE
How to: master and more than default number of PDOs

### ISSUE THREAD

**Issue by mullinsen** [embedded-office/canopen-stack#155]
Hi, I love this project but I’m new to CANopen and struggling to figure out a couple of things.

I found a question from 2022 where someone wanted to use CanOpen Stack for a NMT master node, and the reponse was that CanOpen Stack is intended as «NMT Slave only», but working towards supporting master nodes. Is this still the case? If it now supports both, how to I configure a node to be NMT master?

Second question, I need more than 4 RPDOs in a slave node. However, even though they are all defined in the OD, CanOpen Stack does not seem to process more than the 4 first RPDOs when initializing. How do I configure more than 4 RPDOs/TPDOs?

**Comment by andrewteta** [comment]
I'm also interested in implementing a NMT master node. Any help would be much appreciated!

**Comment by mullinsen** [comment]
@andrewteta I actually found the answers I was looking for in the closed issues:
Multiple PDOs: Define CO_TPDO_N and CO_RPDO_N as the maximum number of *PDOs required. Default value of this is 4 if not defined. 
NMT master is not supported, but workaround suggested here was sufficient for me: https://github.com/embedded-office/canopen-stack/issues/97
