### ISSUE TITLE
What is the expected behavior of a dual SDO Request on a single server?

### ISSUE THREAD

**Issue by Vincrl** [embedded-office/canopen-stack#30]
Hello, I am quite new to CanOpen and learning a lot from your implementation. 

I was wondering if the behavior of a double access on a single server is defined in the 301 standard.

Example:
1. Node 1 requests a segmented upload from the Node 2 via the 0x602 request.
2. The requests arrive to let's say 5/10 segments
3. The Node 3 requests an expedited request via the 0x602 request.

What should happen here? From what I understand of your implementation, the Server 0x602 will accept the request without changing the Active Object because of the Node 1 request uses the same RxID. Will the Node 2 abort the request via a 0x582 answer and therefore kill both Node 1 and Node 3 requests when it realizes the CCS doesn't fit?

My workaround was to declare 2 servers on the Node 2 and make Node 1 communicate via 0x612 and Node 3 via 0x632.
But this solutions seems wrong to me...

Could you guide me toward the proper standard solution or even better did I misunderstand the implementation and this exception is already handled somehow?

Thank you and sorry if I was unclear on some points or lacking in my understanding.

**Comment by michael-hillmann** [comment]
*The specified behavior is defined in chapter "7.2.4.3.2 Protocol SDO download" and "7.2.4.3.5 Protocol SDO Upload" (just for me as a reference).*

In your given example the node 3 aborts the segmented transfer started by node 1. This is the intended behavior and specified in the referenced chapters. In general, the SDO transfer is a peer-to-peer communication between two CANopen devices. Mostly used for configuration and maintenance activities.

Your (so-called) workaround is the correct solution to establish a communication network with SDOs.

Note: Please double-check, if you really want to communicate with SDOs. For operational workload, the most widely used communication is PDO communication.
