### ISSUE TITLE
Question about conformance of this stack

### ISSUE THREAD

**Issue by cjardin112** [embedded-office/canopen-stack#32]
Hi,

I'm currently using your stack for a project on a STM32F0. Works like a charm.

I would like to know if anyone has tested this stack against the CiA conformance test tool ?

Thanks.

Br;

**Comment by michael-hillmann** [comment]
I know one company, who checks their product against the CiA conformance test suite.
Are you going to test your product, too?

**Comment by cjardin112** [comment]
Alright. Yes I'm planning to test the product. I'll get you updated as soon as I can test it ! :)

**Comment by hoantv** [comment]
> Hi,
> 
> I'm currently using your stack for a project on a STM32F0. Works like a charm.
> 
> I would like to know if anyone has tested this stack against the CiA conformance test tool ?
> 
> Thanks.
> 
> Br;

Do you use it with HAL driver.
Currently i write a small library with hal driver. It works but sometime it disconnect to servo drive :(

**Comment by cjardin112** [comment]
Hi @hoantv,

I'm currently using it and haven't noticed any connections issues.

Can you explain your problem here ? Do you have any debugger that you can use for investigations ?

Br;

**Comment by michael-hillmann** [comment]
Closed due to inactivity and missing data for further investigations
