### ISSUE TITLE
Broken RPDO connection

### ISSUE THREAD

**Issue by cjardin112** [embedded-office/canopen-stack#33]
Hi,
I managed to get my TPDO working. But unfortunately, my RPDO seems broken..

From what I found, I think the comparison
 `if ((id & CO_RPDO_COBID_REMOTE) == 0) {
        pdo->Node->Error = CO_ERR_RPDO_COM_OBJ;
        return (CO_ERR_RPDO_COM_OBJ);
    }`
is not relevant in the RPDO initialization process because we do not need the RTR flag like TPDO. (CORPdoReset() co_pdo.c line 549)

As you don't take care of RTR flag in CO_COBID_RPDO_DEFAULT macro, this comparison is always true.
Pull request : #34 

Br;

**Comment by michael-hillmann** [comment]
You are right. The Bit30 is reserved in the RPDO COBID definition. Thank you for your investigation.
