### ISSUE TITLE
is there some example for mcu porting? such as stm32f4 serials microcontrol.

### ISSUE THREAD

**Issue by zhangshengping** [embedded-office/canopen-stack#39]
I want to use this stack on stm32f407 microcontorl, but i can not find some examples.
is there some example for mcu porting?

**Comment by michael-hillmann** [comment]
There is documentation on how to write the small driver functions for CAN, NVM, and Timers.
(see: https://canopen-stack.org/docs/hardware/can)

**Comment by cjardin112** [comment]
Basically, you have to follow ST instructions to get CAN working. Next step is to follow the stacks documentation and implements what needs to be implemented.
