### ISSUE TITLE
Multi-frame Buffer Issue

### ISSUE THREAD

**Issue by f1-stuo** [embedded-office/canopen-stack#44]
Hi,

Device: [S32K116]
OS: [none]
Version [v4.1.5]

In respect to multi-frame CANopen SDO write requests, the buffer pointer (COObjWrBufCont) always only contains the last frame (7 bytes), yet the buffer should contain 127 x 7 bytes. As such it is only possible to access the most recent 7 bytes transmitted. Could you confirm this issue please, and advise if it a planned to be fixed?  

Many thanks,

Stu

**Comment by michael-hillmann** [comment]
Hmm, I don't understand your issue. Assuming you configure the following object entry in your dictionary:

~~~c
// Assuming we want to provide the content of the memory area in Data within an object entry:
uint8_t Data[100]
~~~

There is no basic data type sufficient (INTEGER8, INTEGER32, etc..) so we use the data type "DOMAIN":

~~~c
// Declare CANopen domain for the data
CO_OBJ_DOM DomainData = {
  0,              /* member for read position */
  sizeof(Data),   /* size of domain memory */
  &Data           /* start address of domain memory */
};
~~~

The object entry definition, which allows the data to be read by the CANopen master (or other nodes) is:

~~~c
  :
  { CO_KEY(0x2345, 0, CO_DOMAIN|CO_OBJ____R_), CO_TDOMAIN, (uintptr_t)&DomainData },
  :
~~~
