### ISSUE TITLE
PDO Mapping is Modifiable

### ISSUE THREAD

**Issue by f1-stuo** [embedded-office/canopen-stack#45]
Hi,

Device: [S32K116]
OS: [none]
Version [v4.1.5]

PDO mapping shouldn’t be able to be modified, but the CANopen Stack seems to allow access / changes to the mapping outside of the proper process. I thought it worth mentioning as it leads to CCTT errors.

Kind regards,

Stu

**Comment by michael-hillmann** [comment]
This depends on how you define the object dictionary:

If you want to achieve static PDO mapping, you should define:

~~~c
  :
    {CO_KEY(0x1A00, 0, CO_UNSIGNED8 |CO_OBJ_D__R_), 0, (uintptr_t)3},
    {CO_KEY(0x1A00, 1, CO_UNSIGNED32|CO_OBJ_D__R_), 0, CO_LINK(0x2100, 0x01, 32)},
    {CO_KEY(0x1A00, 2, CO_UNSIGNED32|CO_OBJ_D__R_), 0, CO_LINK(0x2100, 0x02,  8)},
    {CO_KEY(0x1A00, 3, CO_UNSIGNED32|CO_OBJ_D__R_), 0, CO_LINK(0x2100, 0x03,  8)},
  :
~~~

If you need the same but changeable from the CANopen master side, you need to use the corresponding types:

~~~c
   :
uint8_t mapNumVar = 3;
uint32_t mapLinkVar[8] = {
  CO_LINK(0x2100, 0x01, 32),
  CO_LINK(0x2100, 0x02,  8),
  CO_LINK(0x2100, 0x03,  8),
  0L, 0L, 0L, 0L, 0L
};
  :
    {CO_KEY(0x1A00, 0, CO_UNSIGNED8 |CO_OBJ____RW), COTPdoMapN, (uintptr_t)&mapNumVar},
    {CO_KEY(0x1A00, 1, CO_UNSIGNED32|CO_OBJ____RW), COTPdoMap, (uintptr_t)&mapLinkVar[0]},
    {CO_KEY(0x1A00, 2, CO_UNSIGNED32|CO_OBJ____RW), COTPdoMap, (uintptr_t)&mapLinkVar[1]},
    {CO_KEY(0x1A00, 3, CO_UNSIGNED32|CO_OBJ____RW), COTPdoMap, (uintptr_t)&mapLinkVar[2]},
       :
    {CO_KEY(0x1A00, 8, CO_UNSIGNED32|CO_OBJ____RW), COTPdoMap, (uintptr_t)&mapLinkVar[7]},
  :
~~~

Note: If you want to store the configuration in NVM, you can even go further and define the `mapLinkVar` and `mapNumVar` a part of a parameter group.

Hope this helps ;-)
