### ISSUE TITLE
SDO Client functionality

### ISSUE THREAD

**Issue by NebulaDev16** [embedded-office/canopen-stack#65]
We can see in documentation that SDO Client functionality is present in roadmap for the canopen-stack.
We require this functionality in our use case. Can you please share the tentative timeline for the same?

**Comment by michael-hillmann** [comment]
There is no concrete schedule for the SDO client.

**Comment by michael-hillmann** [comment]
Hi, I just want to inform you that the SDO client is available now. Happy coding 👍
