### ISSUE TITLE
Interface Receive API

### ISSUE THREAD

**Issue by NebulaDev16** [embedded-office/canopen-stack#67]
We wanted to know more about Interface Receive COIfCanReceive() API.
As we understand, Will this API be triggered for valid CAN packets which are not intended for the device node id.
For example, if a device with canopen stack and node id 2 are setup. Using this API, can we get packets for SDO transfers between node 3 and node 4?

**Comment by michael-hillmann** [comment]
Yes, all messages which are not consumed by the CANopen stack are triggering the COIfCanReceive() callback function.
