### ISSUE TITLE
NMT CO_RESET_NODE Doesn't provide a way to actually reset the application.

### ISSUE THREAD

**Issue by shersey-locus** [embedded-office/canopen-stack#73]
I'm using the latest master release, and attempting to add a firmware download functionality. 
In my system, firmware downloads are received via SDO and stored in external flash, then the host device is (supposed to be) rebooted; a separate bootloader validates the new application download in external flash (is it intact and newer than the installed firmware?), installs it if necessary, and launches the installed application.
The system works so far, except for one thing: The CANopen NMT command 129 to "reset application (and communication)" doesn't reset the application. This is system-dependent, so I would expect this to be handled by, say, the CONmtModeChange() callback. Unfortunately, CO_RESET_NODE gets reduced to CO_INIT on its way to the callback, so there's no way to implement an actual application reset.  CONmtModeChange() never sees the CO_RESET_NODE mode command at all.
Naturally, I could hack my way around this with the custom data type I use for flash control, but that's ugly. Alternatively, I could hack the CANopen stack source to insert by own callback, but that's unmaintainable. 
Is "reset application" actually intended to let me reset the application the CANopen stack lives in? If so, something is missing, either in the code or in my understanding of it.

**Comment by michael-hillmann** [comment]
Can you have a look to branch **develop**? Is this enhancement covering your use-case?

*Note: The application needs to provide the callback function `CONmtResetRequest()`. Therefore, we change the version tag from 4.1.9 to 4.2.0.*
