### ISSUE TITLE
Mislink in the documentation

### ISSUE THREAD

**Issue by sudoDavi** [embedded-office/canopen-stack#75]
**Describe the bug**
There's a mislink in the documentation hosted on https://canopen-stack.org/docs

*You get a 404 error when clicking the below mentioned button*
![image](https://user-images.githubusercontent.com/12603499/142654839-93f74693-5558-44b9-93f1-66694f129704.png)

**To Reproduce**
If you click the Quickstart link on the topics list on the left, it links you to https://canopen-stack.org/examples/quickstart , but the page for the Quickstart section is located on https://canopen-stack.org/quickstart/
![image](https://user-images.githubusercontent.com/12603499/142654622-d8fd5945-06bb-47f2-8dfb-eb6f7127ab7a.png)

**Expected behavior**
Open the Quickstart page.
![image](https://user-images.githubusercontent.com/12603499/142654927-2d7ba0d7-422c-4e78-8996-8c7a52d4fafb.png)

**Comment by michael-hillmann** [comment]
Thank you for this issue.
A fix is prepared in the development branch and is deployed with next release.

**Comment by michael-hillmann** [comment]
Is constantly improved by switching to Mkdocs (see pull-request #89)
