### ISSUE TITLE
CiA301 related objects implementation 

### ISSUE THREAD

**Issue by sunischit1** [embedded-office/canopen-stack#78]
> I have an question related to CiA301 object implementation i;e such as example heartbeat time, EMCY, inhibit time object. As per my understanding these objects implementation are part of stack itself only we need to create entry in the object dictionary. This is already been tested and verified wrt stack integrated functionality. Please can anyone help on my understanding.

**Comment by michael-hillmann** [comment]
You are right. You just need to configure the object dictionary with the corresponding types and the required functionallity is provided by the stack.
