### ISSUE TITLE
Block transfer abort issue

### ISSUE THREAD

**Issue by Domen2242** [embedded-office/canopen-stack#79]
I am using a custom CO_OBJ_TYPE
my read and write functions handle access to the data.
However, sometimes the data requested by master is not available and I return a result other than CO_ERR_NONE

when that happens:
using expedited transfer - the SDO transfer gets aborted by the CO stack (as expected)
using segmented transfer - the SDO transfer gets aborted by the CO stack (as expected)
using block transfer - the stack replies to the upload request with whatever was in the SDO server's buffer

behaviour is similar for SDO block download as well

**Comment by michael-hillmann** [comment]
The update prepared in branch `develop` should handle this correctly.
