### ISSUE TITLE
In valid abort code is received for object 1003h:00h

### ISSUE THREAD

**Issue by siddamsantosh** [embedded-office/canopen-stack#87]
**Describe the bug**
In valid abort code is received for object 1003h:00h

**To Reproduce**
1. Write value 0h to object 1003h:00h
2. send CAN request
	CAN1  67F Tx SD  8  2F 03 10 00 FF 00 00 00
3. See error
	CAN1  5FF Rx SD  8  80 03 10 00 20 00 00 08
	Received abort code is 08000020h

**Expected behavior**
Valid abort codes are 06090030h, 06090031h or 08000000h.

**Screenshots**
![SDO10](https://user-images.githubusercontent.com/101257830/157433790-d0780a3c-7b56-4e1a-9645-7da29deb9faf.png)

**CANopen Stack (please complete the following information):**
 - Device: NXP S32K116
 - OS: none
 - Version v.4.1.7

**Additional context**
None

**Comment by michael-hillmann** [comment]
Thanks for letting me know this issue. Could you add the relevant object directory entry line(s), please.

**Comment by siddamsantosh** [comment]
Thanks Michael for your quick reply.
I think, these are the  below object directory entry lines you are expecting.  If not, kindly let me know some more details.

#define CO_TEMCY   ((const CO_OBJ_TYPE *)&COTEmcy)    /*!< EMCY History      */
...
...

const CO_OBJ_TYPE COTEmcy = { 0, 0, COTypeEmcyRead, COTypeEmcyWrite };
...
...
/* 004 */ {CO_KEY(0x1003, 0, CO_UNSIGNED8 |CO_OBJ_D__RW),        CO_TEMCY, 0                                     },
/* 005 */ {CO_KEY(0x1003, 1, CO_UNSIGNED32|CO_OBJ_D__R_),        CO_TEMCY, 0                                     },
/* 006 */ {CO_KEY(0x1003, 2, CO_UNSIGNED32|CO_OBJ_D__R_),        CO_TEMCY, 0                                     },
/* 007 */ {CO_KEY(0x1003, 3, CO_UNSIGNED32|CO_OBJ_D__R_),        CO_TEMCY, 0                                     },
/* 008 */ {CO_KEY(0x1003, 4, CO_UNSIGNED32|CO_OBJ_D__R_),        CO_TEMCY, 0                                     },
/* 009 */ {CO_KEY(0x1003, 5, CO_UNSIGNED32|CO_OBJ_D__R_),        CO_TEMCY, 0                                     },
/* 010 */ {CO_KEY(0x1003, 6, CO_UNSIGNED32|CO_OBJ_D__R_),        CO_TEMCY, 0                                     },
/* 011 */ {CO_KEY(0x1003, 7, CO_UNSIGNED32|CO_OBJ_D__R_),        CO_TEMCY, 0                                     },
/* 012 */ {CO_KEY(0x1003, 8, CO_UNSIGNED32|CO_OBJ_D__R_),        CO_TEMCY, 0                                     },
/* 013 */ {CO_KEY(0x1003, 9, CO_UNSIGNED32|CO_OBJ_D__R_),        CO_TEMCY, 0                                     },
